Repository BusHanyang/Shuttle_PWA, pull requests merged in 2020-07, with the labels that each got.

#40 Rebase/integrate api
  .idea/jsLibraryMappings.xml
  package.json
  src/components/OneText.vue
  src/settings.json
  src/util.js
  timetable/Residence_week.json
  timetable/Shuttlecock_week.json
  timetable/Subway_week.json
  timetable/YesulIn_week.json
  yarn.lock
Labels: enhancement

#42 Remove old banner
  src/components/Banner.vue
  src/components/Home.vue
Labels: Front-end, bug

#43 Adding sentry package
  package.json
  src/main.js
  yarn.lock
Labels: dependencies

#45 Change API url to google storage API
  src/components/OneText.vue
Labels: Front-end, enhancement
